name: Check GCC installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check GCC installation
      run: gcc --version

    - name: Build the code
      run: make VERBOSE=1

